INSERT INTO rewards (title, required_points, created_at) VALUES
     ('Bánh kẹo', 50, CURRENT_TIMESTAMP),
     ('Đồ chơi xếp hình', 150, CURRENT_TIMESTAMP),
     ('Bút màu', 70, CURRENT_TIMESTAMP),
     ('Truyện tranh', 100, CURRENT_TIMESTAMP),
     ('Xe đạp nhỏ', 300, CURRENT_TIMESTAMP),
     ('Vé xem phim', 120, CURRENT_TIMESTAMP),
     ('Balo mới', 200, CURRENT_TIMESTAMP),
     ('Bộ lego mini', 250, CURRENT_TIMESTAMP),
     ('Búp bê', 180, CURRENT_TIMESTAMP),
     ('Thú nhồi bông', 90, CURRENT_TIMESTAMP),
     ('Bộ đồ chơi nấu ăn', 160, CURRENT_TIMESTAMP),
     ('Vé đi sở thú', 140, CURRENT_TIMESTAMP),
     ('Đèn ngủ hình thú', 130, CURRENT_TIMESTAMP),
     ('Đồng hồ đeo tay trẻ em', 220, CURRENT_TIMESTAMP),
     ('Bóng đá', 110, CURRENT_TIMESTAMP);
